version: '3'

services:
  db:
    image: postgres:16.2
    container_name: db
     #ports:
      #- "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    networks:
      - devops
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: web:latest
    container_name: web  
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py createsuperuser --no-input  && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASS}
      DB_HOST: db
      DB_PORT: 5432
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_USER}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_PASS}
      DJANGO_SUPERUSER_EMAIL: ${JANGO_EMAIL}
    networks:
      - devops

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - web
    networks:
      - devops

volumes:
  db_data:


networks:
  devops:
